### ISSUE TITLE
Having trouble setting up VPN server

### ISSUE THREAD

**Issue by silentioetfide** [DyonR/docker-sabnzbdvpn#8]
Hello, I am experiencing some difficulty setting up the VPN-server. Can you help? Here's the log.  I don't know how to perform the --help command. Thanks for your kind assistance!

![image](https://user-images.githubusercontent.com/99959590/154661122-4364b51b-e6c4-417a-9984-3a7080c1c6eb.png)

**Comment by DyonR** [comment]
In de logs zie ik dat je `LAN_NETWORK` hebt ingesteld als `192.168.1.1/250`, dat is onjuist.  
Ik neem aan dat je netwerk thuis van `192.168.1.1` tot en met `192.168.1.255` gaat. Je moet `LAN_NETWORK` dan als `192.168.1.0/24` instellen. 
  
Mocht het daarna nog niet werken, dan zie niet direct in de logs wat er nog meer mis gaat.  
Als het dus nog niet werkt, kan je een overzicht doorsturen van alle instellingen van de container, dus alle environment variables zoals `VPN_ENABLED=yes`, `LAN_NETWORK=192.168.1.1/24`, ook de volume paden die je hebt ingestelt voor `/downloads` en `/config`.  
Let wel op dat je niet je VPN gebruikersnaam en wachtwoord dan doorstuurt.  
Sorry voor de late response trouwens, maar vanwege mijn privé leven heb ik niet altijd tijd of zin om gratis ondersteuning te bieden ;)

**Comment by silentioetfide** [comment]
Het probleem is inmiddels opgelost, dank voor je hulp! Ik had nog een reply gestuurd met bijlagen, die ik vervolgens hier als comment zag verschijnen (hoewel zonder de bijlagen). Kun je bevestigen dat deze reply en de bijlagen nu zijn verwijderd? Ik zou het vervelend vinden als die bijlagen ergens online 'slingeren' :-) Bedankt!

**Comment by DyonR** [comment]
> Het probleem is inmiddels opgelost, dank voor je hulp! Ik had nog een reply gestuurd met bijlagen, die ik vervolgens hier als comment zag verschijnen (hoewel zonder de bijlagen). Kun je bevestigen dat deze reply en de bijlagen nu zijn verwijderd? Ik zou het vervelend vinden als die bijlagen ergens online 'slingeren' :-) Bedankt!

Ik kan nergens een reply of bijlage vinden! Goed om te horen dat het opgelost is.
