### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by DrewL4** [DyonR/docker-sabnzbdvpn#9]
I was running latest and lost GUI on update so I switched over to dev and it was running fine until the latest update. What do I need to do to get running again. I have touched nothing in config.

**Comment by DyonR** [comment]
Update the Docker container and it should be working again.  
SABnzbd has a new dependency which was not included in the Docker, causing it not to load. I've included this dependency now, and it all seems to work fine again.

**Comment by DrewL4** [comment]
Worked. Thanks!!!
